### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by Cardridge** [Koward/Improved_Models#4]
I'm a clueless idiot. Please instruct.

**Comment by Koward** [comment]
The useful files are the folders at root (Creature, World...).
You can take them and pack them in a MPQ file with [Ladik's MPQ Editor](http://www.zezula.net/en/mpq/download.html) or use a [modded WoW.exe](http://modcraft.superparanoid.de/viewtopic.php?f=59&t=9218) to load files directly from the Data folder without compression.

**Comment by Cardridge** [comment]
Thanks for the answer.
This issue can be closed unless you want others to see the response as well.
